## Ex:2 Data Wrangling and Transformation 
### Objective

To perform data wrangling and transformation on a dataset using Python and Pandas by handling missing values, removing duplicates, correcting data types, filtering data, and transforming variables into a suitable format for data analysis and machine learning.



##  Dataset Description

The dataset contains information about **student academic performance, educational background, MBA specialization, and placement salary**.

###  Dataset Attributes

| Column | Description |
|:---|:---|
| `sl_no` | Serial number / student identifier |
| `gender` | Gender of the student |
| `hsc_p` | Higher Secondary / 12th percentage |
| `hsc_s` | Higher Secondary stream |
| `degree_p` | Undergraduate degree percentage |
| `degree_t` | Undergraduate degree type |
| `etest_p` | Employability / entrance test percentage |
| `specialisation` | MBA specialization |
| `mba_p` | MBA percentage |
| `salary` | Salary offered after placement |

---

## Experiment Question

 **Using the given student placement dataset, perform data wrangling and transformation by handling missing values, scaling numerical features, detecting and treating outliers, encoding categorical variables, and generating a final model-ready dataset.**

Data wrangling and transformation is the process of converting raw student placement data into a clean, consistent, and machine-learning-ready dataset. In this experiment, the given student placement dataset is first loaded into a Pandas DataFrame and explored by examining its rows, columns, data types, and descriptive statistics. Missing values are then identified and handled by removing records with missing `salary` values and replacing missing values in `hsc_p`, `degree_p`, and `etest_p` with their respective mean values. The numerical attributes such as `hsc_p`, `degree_p`, `etest_p`, and `salary` are transformed using feature-scaling techniques such as `StandardScaler` and `MinMaxScaler` to bring the variables into suitable numerical ranges. The dataset is then divided into input features (`X`) and the target variable (`Y`), where `salary` is considered the target. The preprocessed data is saved as `Pre.csv` for further processing. Next, possible outliers in the `salary` attribute are identified using a boxplot and statistically detected using the Z-score method, where values with an absolute Z-score greater than 3 are considered potential outliers. Outliers are also treated using the capping and flooring method by calculating the 5th and 95th percentiles and replacing values outside these limits with the corresponding boundary values. The salary distribution before and after outlier treatment is then compared using visualization. Since the dataset also contains categorical attributes such as `gender`, `hsc_s`, `degree_t`, and `specialisation`, these variables are converted into numerical representations using `LabelEncoder` and One-Hot Encoding. Finally, the completely transformed dataset is verified for missing values, data types, dimensions, and numerical representation, and the resulting model-ready dataset is saved as `Final.csv`. Thus, the experiment demonstrates the complete workflow of preparing real-world tabular data for data analysis and machine-learning applications.

## Step 1: Start by importing the necessary Python libraries for data preprocessing.

In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from scipy.stats import zscore
from scipy import stats
from sklearn.preprocessing import LabelEncoder

## Step 2: Load the placement dataset into a Pandas Dataframe.

In [22]:
df = pd.read_csv("data.csv")

,sl_no,gender,hsc_p,hsc_s,degree_p,degree_t,etest_p,specialisation,mba_p,salary
1,2,M,78.33,Science,77.48,Sci&Tech,86.5,Mkt&Fin,66.28,200000.0
2,3,M,NaN,Arts,64.00,Comm&Mgmt,75.0,Mkt&Fin,57.80,250000.0
3,4,M,52.00,Science,NaN,Sci&Tech,66.0,Mkt&HR,59.43,NaN

## Step 3:Take a quick look at the data to understand its structure and identify any missing values or anomalies.

In [ ]:
df.info()

In [ ]:
df.shape

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.sample(5)

In [ ]:
df.describe()

In [ ]:
df.loc[[1,2,3,4,5,6]]
df.iloc[[1,2,3]]

#### The method isnull() checks each element in the DataFrame (or Series) to see if it is NaN (Not a Number) or None (missing value).
It returns a DataFrame (or Series) of the same shape as the input, with Boolean values:
#### True: The value is null (NaN or None).
#### False: The value is not null.

In [ ]:
df.isnull().sum()

## Step 4: Handle Missing Data
### Option 1: If the dataset is large and only a small percentage of data is missing, you can remove rows with missing values using dropna(subset,inplace)

In [ ]:
df = pd.read_csv("data.csv")
df[0:2]
df["degree_t"]
df.dropna(subset=["salary"],inplace=True)

In [ ]:
df.isnull().sum()

### Option 2:If removing data isn't ideal, you can impute (df.[""].fillna(df[""].mean(),inplace)) missing values using methods like mean, median, or most frequent.

In [38]:
df[0:214]
df["hsc_p"]=df["hsc_p"].fillna(df["hsc_p"].mean())
df["degree_p"]=df["degree_p"].fillna(df["degree_p"].mean())
df["etest_p"]=df["etest_p"].fillna(df["etest_p"].mean())
df.isnull().sum()

sl_no             0
gender            0
hsc_p             0
hsc_s             0
degree_p          0
degree_t          0
etest_p           0
specialisation    0
mba_p             0
salary            0
dtype: int64

## Step 5: Feature Scaling
Feature scaling is the process of converting numerical features to a similar scale so that one feature does not dominate another simply because it has larger numerical values.

<img src="https://i.postimg.cc/G21gMYnF/f.png" alt="Image Description" width="500">









## Option 1( StandardScaler): This method scales the data to have a mean of 0 and a standard deviation of 1.

In [44]:
c=["hsc_p","degree_p","etest_p","salary"]
sc1=StandardScaler()
df[c]=sc1.fit_transform(df[c])
df.head

<bound method NDFrame.head of      sl_no gender         hsc_p     hsc_s  degree_p   degree_t   etest_p  \
0        1      M  2.265997e+00  Commerce -1.652293   Sci&Tech -1.328518
1        2      M  8.987875e-01   Science  1.346845   Sci&Tech  0.978332
2        3      M  1.533482e-15      Arts -0.728534  Comm&Mgmt  0.136149
4        5      M  3.883770e-01  Commerce  0.703293  Comm&Mgmt  1.732635
7        8      M -6.475513e-01   Science -0.420614   Sci&Tech -0.449718
..     ...    ...           ...       ...       ...        ...       ...
209    210      M  2.157223e-01  Commerce -0.574574  Comm&Mgmt -0.449718
210    211      M  1.294814e+00  Commerce  1.365320  Comm&Mgmt  1.307882
211    212      M -1.079188e+00   Science  0.503145   Sci&Tech  0.062915
212    213      M -3.238237e-01  Commerce  0.657105  Comm&Mgmt -1.035584
213    214      F -4.317329e-01  Commerce -1.652293  Comm&Mgmt -0.230018

    specialisation  mba_p    salary
0           Mkt&HR  58.80 -0.200292
1          Mkt&Fin  66.28 -0.951839
2          Mkt&Fin  57.80 -0.415019
4          Mkt&Fin  55.50  1.463849
7          Mkt&Fin  62.14 -0.393547
..             ...    ...       ...
209        Mkt&Fin  56.49 -0.780057
210        Mkt&Fin  74.49  1.195439
211        Mkt&Fin  53.62 -0.146610
212        Mkt&Fin  69.72  0.068118
213         Mkt&HR  60.23 -0.908893

[148 rows x 10 columns]>

#### Option 2:This method scales the data to a fixed range, usually between 0 and 1. 
###  MinMaxScaler()

In [50]:
c=["hsc_p","degree_p","etest_p","salary"]
sc1=MinMaxScaler()
df[c]=sc1.fit_transform(df[c])

## Step 6  Option 1: Identifying Outliers Using Z-Scores
The value of 3 in the context of Z-scores is often used as a threshold to identify outliers in a dataset. A Z-score represents how many standard deviations a data point is away from the mean of the dataset. Specifically:

A Z-score of 0 means the data point is exactly at the mean.
A Z-score of 1 means the data point is one standard deviation above the mean, and so on.
A Z-score of 3 corresponds to a data point being 3 standard deviations away from the mean. For a normal distribution, about 99.7% of the data points fall within 3 standard deviations of the mean (according to the 68-95-99.7 rule, which describes the spread of data in a normal distribution). Therefore, points with Z-scores greater than 3 or less than -3 are considered unusually far from the mean and are often flagged as outliers.

This threshold (Z > 3 or Z < -3) is commonly used in many statistical applications because it captures the extreme values that are rare in a normal distribution, which are typically considered to be outliers. However, the choice of threshold can vary depending on the specific application and the nature of the data.

[![Chat-GPT-Image-Aug-20-2026-08-06-05-PM.png](https://i.postimg.cc/2SFTtcXL/Chat-GPT-Image-Aug-20-2026-08-06-05-PM.png)](https://postimg.cc/4Yyz75GX)

In [68]:
columns_to_check=["salary"]
z_score = stats.zscore(df[columns_to_check])
#print(z_score)
u = (z_score>3)
l = (z_score<-3)
index = u | l
# print(u)
# print(l)
clean_df = df[~index]
df.info(), clean_df.info()

<class 'pandas.DataFrame'>
Index: 148 entries, 0 to 213
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           148 non-null    int64
 1   gender          148 non-null    str
 2   hsc_p           148 non-null    float64
 3   hsc_s           148 non-null    str
 4   degree_p        148 non-null    float64
 5   degree_t        148 non-null    str
 6   etest_p         148 non-null    float64
 7   specialisation  148 non-null    str
 8   mba_p           148 non-null    float64
 9   salary          148 non-null    float64
dtypes: float64(5), int64(1), str(4)
memory usage: 12.7 KB
<class 'pandas.DataFrame'>
Index: 145 entries, 0 to 213
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           145 non-null    int64
 1   gender          145 non-null    str
 2   hsc_p           145 non-null    float64
 3   hsc_s           145 non-null    str
 4   degree_p        145 non-null    float64
 5   degree_t        145 non-null    str
 6   etest_p         145 non-null    float64
 7   specialisation  145 non-null    str
 8   mba_p           145 non-null    float64
 9   salary          145 non-null    float64
dtypes: float64(5), int64(1), str(4)
memory usage: 12.5 KB

(None, None)

### Option 2:  Capping and Flooring Outliers
Capping and flooring is an outlier-treatment technique where extreme values are replaced with predefined boundary values instead of deleting the records.

In [74]:
l1 = df["salary"].quantile(0.05)
u1 = df["salary"].quantile(0.95)

df_capped = df.copy()
# df_capped["salary"] = df_capped["salary"].clip(lower=l1, upper=u1)
df_capped["salary"] = df_capped["salary"].clip(l1, u1)
df_capped.info()
df.head()

<class 'pandas.DataFrame'>
Index: 148 entries, 0 to 213
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           148 non-null    int64
 1   gender          148 non-null    str
 2   hsc_p           148 non-null    float64
 3   hsc_s           148 non-null    str
 4   degree_p        148 non-null    float64
 5   degree_t        148 non-null    str
 6   etest_p         148 non-null    float64
 7   specialisation  148 non-null    str
 8   mba_p           148 non-null    float64
 9   salary          148 non-null    float64
dtypes: float64(5), int64(1), str(4)
memory usage: 12.7 KB

,sl_no,gender,hsc_p,hsc_s,degree_p,degree_t,etest_p,specialisation,mba_p,salary
0,1,M,0.857051,Commerce,0.057143,Sci&Tech,0.104167,Mkt&HR,58.80,0.094595
1,2,M,0.586729,Science,0.613714,Sci&Tech,0.760417,Mkt&Fin,66.28,0.000000
2,3,M,0.409023,Arts,0.228571,Comm&Mgmt,0.520833,Mkt&Fin,57.80,0.067568
4,5,M,0.485812,Commerce,0.494286,Comm&Mgmt,0.975000,Mkt&Fin,55.50,0.304054
7,8,M,0.280990,Science,0.285714,Sci&Tech,0.354167,Mkt&Fin,62.14,0.070270

## Step 7: Convert categorical variables into numerical format using LabelEncoder ().
[![Picture1.png](https://i.postimg.cc/yNpNvnVd/Picture1.png)](https://postimg.cc/zLW5fCHZ)

In [78]:
l1 = LabelEncoder()
df["gender"]=l1.fit_transform(df["gender"])
df["hsc_s"]=l1.fit_transform(df["hsc_s"])
df["degree_t"]=l1.fit_transform(df["degree_t"])
df["specialisation"]=l1.fit_transform(df["specialisation"])
df.head()

,sl_no,gender,hsc_p,hsc_s,degree_p,degree_t,etest_p,specialisation,mba_p,salary
0,1,1,0.857051,1,0.057143,2,0.104167,1,58.80,0.094595
1,2,1,0.586729,2,0.613714,2,0.760417,0,66.28,0.000000
2,3,1,0.409023,0,0.228571,0,0.520833,0,57.80,0.067568
4,5,1,0.485812,1,0.494286,0,0.975000,0,55.50,0.304054
7,8,1,0.280990,2,0.285714,2,0.354167,0,62.14,0.070270

## Convert categorical variables into numerical format using one hot encoder

[![Picture2.png](https://i.postimg.cc/gcZ0Hv1J/Picture2.png)](https://postimg.cc/HjTHp7YD)

In [83]:
c =["gender"]
one_hot_encoded_data = pd.get_dummies(df,columns=c)
one_hot_encoded_data.to_csv('clean.csv', index=False)
Y = df["salary"].copy()
X = df.drop(columns = ["salary","sl_no"]).copy()
display(X)
display(Y)

,gender,hsc_p,hsc_s,degree_p,degree_t,etest_p,specialisation,mba_p
0,1,0.857051,1,0.057143,2,0.104167,1,58.80
1,1,0.586729,2,0.613714,2,0.760417,0,66.28
2,1,0.409023,0,0.228571,0,0.520833,0,57.80
4,1,0.485812,1,0.494286,0,0.975000,0,55.50
7,1,0.280990,2,0.285714,2,0.354167,0,62.14
...,...,...,...,...,...,...,...,...
209,1,0.451675,1,0.257143,0,0.354167,0,56.49
210,1,0.665031,1,0.617143,0,0.854167,0,74.49
211,1,0.195648,2,0.457143,2,0.500000,0,53.62
212,1,0.344997,1,0.485714,0,0.187500,0,69.72
213,0,0.323661,1,0.057143,0,0.416667,1,60.23

0      0.094595
1      0.000000
2      0.067568
4      0.304054
7      0.070270
         ...
209    0.021622
210    0.270270
211    0.101351
212    0.128378
213    0.005405
Name: salary, Length: 148, dtype: float64